version: "3.9"
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - 11434
    ports:
      - "11434:11434"
    # restart: always

  redis:
    image: redis:5
    container_name: redis
    environment:
      REDIS_REPLICATION_MODE: master
    # ports:
    #   - "6378:6379"

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    depends_on:
      - ollama
    environment:
      TELEGRAM_BOT_TOKEN: 6059954498:AAHKo5u9S7jgBxaMHIHbIPVJlnVljXfK4I8
      #OLLAMA_HOST: 0.0.0.0
    ports:
      - "8080:8080"
    # restart: always

networks:
  default:
    driver: bridge
